# pod-defination.yml
apiVersion: v1
kind: ReplicationController
metadata:
 name: httpd-pod
spec:
 replicas: 3
 selector:
  app: httpd-app
 template: 
  metadata:
   name: httpd-pod
   labels:
    app: httpd-app
  spec:
   containers: 
   - name: httpd-container
     image: httpd
     ports:
      - containerPort: 80
        hostPort: 8081 
       
       
#kubectl apply -f httpd-rc.yml
#kubectl get pods
#kubectl get pods -l app=httpd-app
#kubectl describe rc nginx-rc
#kubectl get pod -o wide
#kubectl scale rc httpd-rc --replicas=5
#kubectl scale rc httpd-rc --replicas=3
#kubectl delete  -f httpd-rc.yml
