#!/bin/bash
kubectl run nginx --image=nginx
kubectl get pods
kubectl describe  pod nginx
kubectl get pods -o wide
kubectl delete pod nginx

kubectl run my-app --image=httpda
kubectl describe pod my-app ( events )


#Interacting with running Pods
kubectl logs my-pod                                 # dump pod logs (stdout)
kubectl logs -l name=myLabel                        # dump pod logs, with label name=myLabel (stdout)
kubectl logs my-pod -c my-container                 # dump pod container logs (stdout, multi-container case)


